### ISSUE TITLE
ERROR: archive is not a ZIP archive

### ISSUE THREAD

**Issue by NedNedyalkov** [jenkinsci/xray-connector-plugin#16] opened 2020-03-26 09:23 UTC
When using export features option the plugin seems to think the resulting feature file should be an archive.

This is my pipeline step:
```
step([$class: 'XrayExportBuilder',
filePath: '\\Features',
issues: "${params.IssueId}",
serverInstance: 'valid server intance'])
```

This is the log of the execution:
```
Starting XRAY: Cucumber Features Export Task...
##########################################################
####   Xray is exporting the feature files  ####
##########################################################
Issues: <my issues filter>
Will save the feature files in: \Features
###################### Unzipping file ####################
ERROR: archive is not a ZIP archive
XRAY_IS_REQUEST_SUCCESSFUL: false
XRAY_RAW_RESPONSE: 
XRAY_TEST_EXECS: 
XRAY_TESTS: 
XRAY_ISSUES_MODIFIED: 
```

When using postman to do Rest API request with the same issue Id I receive a feature file by default and I need to specify `fz=true` if I want a zip. But this parameter seems missing in the plugin.

**Comment by Russell616** [comment] 2020-03-26 09:58
HI,

Thank you for using our plugin!

Can you tell me what version of:
- Jenkins instance,
- Xray for Jira
- Xray-connector plugin

Thank you.

**Comment by NedNedyalkov** [comment] 2020-03-26 11:18
Hi Rusell,

These are the current versions:
-    Jenkins instance - 2.191
-    Xray for Jira - 3.6.3
-    Xray-connector plugin - 2.2.0

Cheers.

**Comment by Russell616** [comment] 2020-03-26 15:07
Hi

We are unable to reproduce your problem. Since we may require additional information in order to recreate and understand your issue, I suggest you to open a support ticket at our official Xray service desk website: https://xraysupport.xpand-it.com/

Please mentioned in the support ticket this GitHub issue.

I will now close this issue, but feel free to re-open it if you have any more questions.

**Closed by Russell616** 2020-03-26 15:07 UTC

**Comment by ghofraneCh** [comment] 2021-07-29 09:25
Hello NedNedyalkov,
Did you fix the problem please ? 
Thanx,

**Comment by Russell616** [comment] 2021-07-29 09:38
hi @ghofraneCh 

I believe that you already opened a support ticket with our team. If so, lets continue to talk in there since in order us to understand better your problem it may require sharing some sensitive information (like that feature files that you are trying to import).

Otherwise, please create a new support ticket with us here: https://jira.getxray.app/servicedesk/customer/portal/2

**Comment by ghofraneCh** [comment] 2021-07-29 09:43
Ok @Russell616
